export default function handler(req, res) {
  res.status(200).json([
    {
      "id": 1,
      "name": "Cheeseburger Wendy's Burger",
      "description": "Classic fast food burger with fresh ground beef, melted cheese, crispy lettuce, ripe tomatoes, pickles, and our signature sauce on a toasted sesame seed bun.",
      "price": 8.24,
      "rating": 4.5,
      "reviews": 285,
      "image": "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80",
      "category": "Burgers",
      "ingredients": [
        "Beef Patty",
        "Cheese",
        "Lettuce",
        "Tomato",
        "Pickles",
        "Sesame Bun"
      ],
      "calories": 540,
      "preparationTime": "8-12 minutes",
      "spicyLevel": 1,
      "vegetarian": false,
      "available": true
    },
    {
      "id": 2,
      "name": "Hamburger Veggie Burger",
      "description": "Enjoy our delicious Hamburger Veggie Burger made with a plant-based patty, fresh vegetables, and served on a whole wheat bun. Perfect for vegetarians!",
      "price": 9.99,
      "rating": 4.6,
      "reviews": 312,
      "image": "https://images.unsplash.com/photo-1606755962773-0e0b18fc66e0?auto=format&fit=crop&w=800&q=80",
      "category": "Burgers",
      "ingredients": [
        "Plant-Based Patty",
        "Lettuce",
        "Tomato",
        "Onion",
        "Avocado",
        "Whole Wheat Bun"
      ],
      "calories": 420,
      "preparationTime": "6-10 minutes",
      "spicyLevel": 0,
      "vegetarian": true,
      "available": true
    },
    {
      "id": 3,
      "name": "Margherita Pizza",
      "description": "Traditional Italian pizza with fresh mozzarella, tomato sauce, and basil leaves on a thin crust base.",
      "price": 12.5,
      "rating": 4.7,
      "reviews": 456,
      "image": "https://images.unsplash.com/photo-1548365328-5b4f0c1a9d1a?auto=format&fit=crop&w=800&q=80",
      "category": "Pizza",
      "ingredients": [
        "Mozzarella",
        "Tomato Sauce",
        "Fresh Basil",
        "Thin Crust"
      ],
      "calories": 650,
      "preparationTime": "15-20 minutes",
      "spicyLevel": 0,
      "vegetarian": true,
      "available": true
    },
    {
      "id": 4,
      "name": "Pepperoni Pizza",
      "description": "Cheesy pizza topped with spicy pepperoni slices and rich tomato sauce on a crispy base.",
      "price": 13.0,
      "rating": 4.6,
      "reviews": 298,
      "image": "https://images.unsplash.com/photo-1604382354936-07c5e92f4f9f?auto=format&fit=crop&w=800&q=80",
      "category": "Pizza",
      "ingredients": [
        "Mozzarella",
        "Tomato Sauce",
        "Pepperoni",
        "Thin Crust"
      ],
      "calories": 720,
      "preparationTime": "15-18 minutes",
      "spicyLevel": 2,
      "vegetarian": false,
      "available": true
    },
    {
      "id": 5,
      "name": "Grilled Chicken Salad",
      "description": "Fresh mixed greens topped with grilled chicken breast, cherry tomatoes, cucumber, and our house vinaigrette.",
      "price": 11.75,
      "rating": 4.4,
      "reviews": 198,
      "image": "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=800&q=80",
      "category": "Salads",
      "ingredients": [
        "Grilled Chicken",
        "Mixed Greens",
        "Cherry Tomatoes",
        "Cucumber",
        "Vinaigrette"
      ],
      "calories": 320,
      "preparationTime": "5-8 minutes",
      "spicyLevel": 0,
      "vegetarian": false,
      "available": true
    },
    {
      "id": 6,
      "name": "Caesar Salad",
      "description": "Romaine lettuce tossed with creamy Caesar dressing, croutons, and shaved Parmesan cheese.",
      "price": 10.0,
      "rating": 4.5,
      "reviews": 210,
      "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
      "category": "Salads",
      "ingredients": [
        "Romaine Lettuce",
        "Caesar Dressing",
        "Croutons",
        "Parmesan"
      ],
      "calories": 280,
      "preparationTime": "5-7 minutes",
      "spicyLevel": 0,
      "vegetarian": true,
      "available": true
    },
    {
      "id": 7,
      "name": "Spicy Buffalo Wings",
      "description": "Crispy chicken wings tossed in our signature spicy buffalo sauce, served with celery sticks and blue cheese dip.",
      "price": 13.99,
      "rating": 4.8,
      "reviews": 524,
      "image": "https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&w=800&q=80",
      "category": "Appetizers",
      "ingredients": [
        "Chicken Wings",
        "Buffalo Sauce",
        "Celery",
        "Blue Cheese Dip"
      ],
      "calories": 480,
      "preparationTime": "12-15 minutes",
      "spicyLevel": 4,
      "vegetarian": false,
      "available": true
    },
    {
      "id": 8,
      "name": "Nachos Supreme",
      "description": "Crispy tortilla chips topped with melted cheese, jalapeños, guacamole, and sour cream.",
      "price": 9.5,
      "rating": 4.3,
      "reviews": 176,
      "image": "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?auto=format&fit=crop&w=800&q=80",
      "category": "Appetizers",
      "ingredients": [
        "Tortilla Chips",
        "Cheddar",
        "Jalapeños",
        "Guacamole",
        "Sour Cream"
      ],
      "calories": 610,
      "preparationTime": "8-12 minutes",
      "spicyLevel": 3,
      "vegetarian": true,
      "available": true
    },
    {
      "id": 9,
      "name": "Fish & Chips",
      "description": "Beer-battered cod served with crispy fries, mushy peas, and tartar sauce. A British classic!",
      "price": 15.25,
      "rating": 4.3,
      "reviews": 267,
      "image": "https://images.unsplash.com/photo-1617196037305-5d17e27a8a1b?auto=format&fit=crop&w=800&q=80",
      "category": "Seafood",
      "ingredients": [
        "Cod Fish",
        "Beer Batter",
        "Fries",
        "Mushy Peas",
        "Tartar Sauce"
      ],
      "calories": 720,
      "preparationTime": "15-18 minutes",
      "spicyLevel": 0,
      "vegetarian": false,
      "available": false
    },
    {
      "id": 10,
      "name": "Grilled Salmon",
      "description": "Fresh salmon fillet grilled to perfection, served with lemon butter sauce and steamed vegetables.",
      "price": 18.0,
      "rating": 4.7,
      "reviews": 221,
      "image": "https://images.unsplash.com/photo-1604908812603-8d3f9b499d1a?auto=format&fit=crop&w=800&q=80",
      "category": "Seafood",
      "ingredients": [
        "Salmon Fillet",
        "Lemon Butter",
        "Vegetables"
      ],
      "calories": 540,
      "preparationTime": "12-16 minutes",
      "spicyLevel": 0,
      "vegetarian": false,
      "available": true
    },
    {
      "id": 11,
      "name": "Classic Spaghetti Bolognese",
      "description": "Authentic Italian spaghetti served with rich, slow-cooked beef and tomato sauce topped with Parmesan cheese.",
      "price": 14.5,
      "rating": 4.7,
      "reviews": 389,
      "image": "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?auto=format&fit=crop&w=800&q=80",
      "category": "Pasta",
      "ingredients": [
        "Spaghetti",
        "Ground Beef",
        "Tomato Sauce",
        "Parmesan",
        "Olive Oil",
        "Garlic"
      ],
      "calories": 680,
      "preparationTime": "14-18 minutes",
      "spicyLevel": 1,
      "vegetarian": false,
      "available": true
    },
    {
      "id": 12,
      "name": "Vegetable Lasagna",
      "description": "Layers of pasta sheets with roasted vegetables, ricotta cheese, spinach, and rich marinara sauce.",
      "price": 13.0,
      "rating": 4.6,
      "reviews": 245,
      "image": "https://images.unsplash.com/photo-1543353071-873f17a7a088?auto=format&fit=crop&w=800&q=80",
      "category": "Pasta",
      "ingredients": [
        "Pasta Sheets",
        "Zucchini",
        "Eggplant",
        "Ricotta",
        "Spinach",
        "Marinara Sauce"
      ],
      "calories": 610,
      "preparationTime": "18-22 minutes",
      "spicyLevel": 0,
      "vegetarian": true,
      "available": true
    },
    {
      "id": 13,
      "name": "Tom Yum Soup",
      "description": "Traditional Thai hot and sour soup with shrimp, lemongrass, mushrooms, and chili paste.",
      "price": 10.5,
      "rating": 4.4,
      "reviews": 178,
      "image": "https://images.unsplash.com/photo-1625943433907-fb7b2eaa8a5b?auto=format&fit=crop&w=800&q=80",
      "category": "Soups",
      "ingredients": [
        "Shrimp",
        "Lemongrass",
        "Mushrooms",
        "Chili Paste",
        "Lime",
        "Fish Sauce"
      ],
      "calories": 250,
      "preparationTime": "8-12 minutes",
      "spicyLevel": 5,
      "vegetarian": false,
      "available": true
    },
    {
      "id": 14,
      "name": "Minestrone Soup",
      "description": "Classic Italian soup with mixed vegetables, beans, pasta, and tomato broth.",
      "price": 9.25,
      "rating": 4.2,
      "reviews": 134,
      "image": "https://images.unsplash.com/photo-1607276170684-2a5e04a3d5e1?auto=format&fit=crop&w=800&q=80",
      "category": "Soups",
      "ingredients": [
        "Carrots",
        "Beans",
        "Celery",
        "Tomato Broth",
        "Pasta",
        "Spinach"
      ],
      "calories": 190,
      "preparationTime": "6-9 minutes",
      "spicyLevel": 0,
      "vegetarian": true,
      "available": true
    },
    {
      "id": 15,
      "name": "Chocolate Lava Cake",
      "description": "Warm chocolate cake with a gooey molten center, served with vanilla ice cream.",
      "price": 7.5,
      "rating": 4.9,
      "reviews": 512,
      "image": "https://images.unsplash.com/photo-1606851091807-5d41a2c69d54?auto=format&fit=crop&w=800&q=80",
      "category": "Desserts",
      "ingredients": [
        "Dark Chocolate",
        "Flour",
        "Eggs",
        "Sugar",
        "Butter",
        "Vanilla Ice Cream"
      ],
      "calories": 420,
      "preparationTime": "10-12 minutes",
      "spicyLevel": 0,
      "vegetarian": true,
      "available": true
    },
    {
      "id": 16,
      "name": "New York Cheesecake",
      "description": "Rich and creamy cheesecake with a graham cracker crust, topped with fresh strawberries.",
      "price": 8.0,
      "rating": 4.8,
      "reviews": 332,
      "image": "https://images.unsplash.com/photo-1601972599720-bd4b7f2a26b6?auto=format&fit=crop&w=800&q=80",
      "category": "Desserts",
      "ingredients": [
        "Cream Cheese",
        "Graham Cracker",
        "Sugar",
        "Strawberries",
        "Eggs"
      ],
      "calories": 500,
      "preparationTime": "No-cook (pre-made)",
      "spicyLevel": 0,
      "vegetarian": true,
      "available": true
    },
    {
      "id": 17,
      "name": "Mango Smoothie",
      "description": "Refreshing smoothie made with fresh mango, yogurt, and honey.",
      "price": 5.75,
      "rating": 4.6,
      "reviews": 214,
      "image": "https://images.unsplash.com/photo-1577803645773-f96470509666?auto=format&fit=crop&w=800&q=80",
      "category": "Drinks",
      "ingredients": [
        "Mango",
        "Yogurt",
        "Honey",
        "Ice"
      ],
      "calories": 180,
      "preparationTime": "3-5 minutes",
      "spicyLevel": 0,
      "vegetarian": true,
      "available": true
    },
    {
      "id": 18,
      "name": "Iced Coffee",
      "description": "Cold brewed coffee served over ice with a splash of milk and sugar.",
      "price": 4.25,
      "rating": 4.3,
      "reviews": 190,
      "image": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80",
      "category": "Drinks",
      "ingredients": [
        "Cold Brew Coffee",
        "Milk",
        "Sugar",
        "Ice"
      ],
      "calories": 90,
      "preparationTime": "2-4 minutes",
      "spicyLevel": 0,
      "vegetarian": true,
      "available": true
    },
    {
      "id": 19,
      "name": "Shrimp Tacos",
      "description": "Grilled shrimp with spicy aioli, cabbage slaw, and lime in soft tortillas.",
      "price": 12.0,
      "rating": 4.7,
      "reviews": 268,
      "image": "https://images.unsplash.com/photo-1543339308-43f5b68e8d5f?auto=format&fit=crop&w=800&q=80",
      "category": "Tacos",
      "ingredients": [
        "Shrimp",
        "Tortilla",
        "Cabbage Slaw",
        "Aioli",
        "Lime"
      ],
      "calories": 450,
      "preparationTime": "10-14 minutes",
      "spicyLevel": 3,
      "vegetarian": false,
      "available": true
    },
    {
      "id": 20,
      "name": "Beef Tacos",
      "description": "Seasoned ground beef served with cheddar cheese, lettuce, salsa, and sour cream in crispy shells.",
      "price": 11.25,
      "rating": 4.5,
      "reviews": 322,
      "image": "https://images.unsplash.com/photo-1604909053197-3f2dbd58c8b5?auto=format&fit=crop&w=800&q=80",
      "category": "Tacos",
      "ingredients": [
        "Ground Beef",
        "Crispy Taco Shell",
        "Cheddar Cheese",
        "Lettuce",
        "Sour Cream",
        "Salsa"
      ],
      "calories": 520,
      "preparationTime": "8-12 minutes",
      "spicyLevel": 2,
      "vegetarian": false,
      "available": true
    },
    {
      "id": 21,
      "name": "Club Sandwich",
      "description": "Triple-layer sandwich with turkey, bacon, lettuce, tomato, and mayonnaise, served with fries.",
      "price": 9.5,
      "rating": 4.4,
      "reviews": 144,
      "image": "https://images.unsplash.com/photo-1550317138-10000687a72b?auto=format&fit=crop&w=800&q=80",
      "category": "Sandwiches",
      "ingredients": [
        "Turkey",
        "Bacon",
        "Lettuce",
        "Tomato",
        "Mayonnaise",
        "White Bread"
      ],
      "calories": 610,
      "preparationTime": "6-9 minutes",
      "spicyLevel": 0,
      "vegetarian": false,
      "available": true
    },
    {
      "id": 22,
      "name": "Falafel Wrap",
      "description": "Middle Eastern wrap with falafel balls, hummus, pickled vegetables, and tahini sauce.",
      "price": 8.75,
      "rating": 4.6,
      "reviews": 177,
      "image": "https://images.unsplash.com/photo-1523986371872-9d3ba2e2e1f1?auto=format&fit=crop&w=800&q=80",
      "category": "Sandwiches",
      "ingredients": [
        "Falafel",
        "Pita Bread",
        "Hummus",
        "Pickled Vegetables",
        "Tahini Sauce"
      ],
      "calories": 450,
      "preparationTime": "5-7 minutes",
      "spicyLevel": 1,
      "vegetarian": true,
      "available": true
    },
    {
      "id": 23,
      "name": "Pancake Stack",
      "description": "Fluffy pancakes stacked with butter, maple syrup, and seasonal berries.",
      "price": 7.25,
      "rating": 4.8,
      "reviews": 288,
      "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
      "category": "Breakfast",
      "ingredients": [
        "Flour",
        "Eggs",
        "Milk",
        "Butter",
        "Maple Syrup",
        "Berries"
      ],
      "calories": 520,
      "preparationTime": "7-10 minutes",
      "spicyLevel": 0,
      "vegetarian": true,
      "available": true
    },
    {
      "id": 24,
      "name": "English Breakfast",
      "description": "Hearty breakfast plate with eggs, bacon, sausage, baked beans, tomato, and toast.",
      "price": 11.0,
      "rating": 4.7,
      "reviews": 365,
      "image": "https://images.unsplash.com/photo-1493770348161-369560ae357d?auto=format&fit=crop&w=800&q=80",
      "category": "Breakfast",
      "ingredients": [
        "Eggs",
        "Bacon",
        "Sausage",
        "Baked Beans",
        "Tomato",
        "Toast"
      ],
      "calories": 820,
      "preparationTime": "10-15 minutes",
      "spicyLevel": 0,
      "vegetarian": false,
      "available": true
    },
    {
      "id": 25,
      "name": "Sushi Platter",
      "description": "Assorted sushi selection including nigiri and maki rolls with fresh fish.",
      "price": 19.5,
      "rating": 4.8,
      "reviews": 402,
      "image": "https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&w=800&q=80",
      "category": "Asian",
      "ingredients": [
        "Rice",
        "Nori",
        "Salmon",
        "Tuna",
        "Avocado",
        "Soy Sauce"
      ],
      "calories": 560,
      "preparationTime": "12-18 minutes",
      "spicyLevel": 1,
      "vegetarian": false,
      "available": true
    },
    {
      "id": 26,
      "name": "Chicken Ramen",
      "description": "Comforting Japanese ramen with chicken broth, noodles, sliced chicken, egg, and scallions.",
      "price": 13.75,
      "rating": 4.7,
      "reviews": 318,
      "image": "https://images.unsplash.com/photo-1604908177353-295b3b0b2d89?auto=format&fit=crop&w=800&q=80",
      "category": "Asian",
      "ingredients": [
        "Ramen Noodles",
        "Chicken Broth",
        "Chicken",
        "Egg",
        "Scallions",
        "Nori"
      ],
      "calories": 600,
      "preparationTime": "12-16 minutes",
      "spicyLevel": 1,
      "vegetarian": false,
      "available": true
    },
    {
      "id": 27,
      "name": "Ribeye Steak",
      "description": "Juicy ribeye steak grilled to order, served with herb butter and roasted potatoes.",
      "price": 24.0,
      "rating": 4.9,
      "reviews": 275,
      "image": "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80",
      "category": "Grill",
      "ingredients": [
        "Ribeye Steak",
        "Herb Butter",
        "Potatoes",
        "Garlic",
        "Rosemary"
      ],
      "calories": 880,
      "preparationTime": "14-20 minutes",
      "spicyLevel": 0,
      "vegetarian": false,
      "available": true
    },
    {
      "id": 28,
      "name": "Butter Chicken",
      "description": "Creamy tomato-based curry with tender chicken pieces, served with basmati rice.",
      "price": 14.25,
      "rating": 4.8,
      "reviews": 341,
      "image": "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=800&q=80",
      "category": "Asian",
      "ingredients": [
        "Chicken",
        "Tomato",
        "Cream",
        "Butter",
        "Spices",
        "Basmati Rice"
      ],
      "calories": 740,
      "preparationTime": "14-18 minutes",
      "spicyLevel": 2,
      "vegetarian": false,
      "available": true
    },
    {
      "id": 29,
      "name": "Greek Salad",
      "description": "Refreshing salad with cucumber, tomatoes, olives, feta cheese, and olive oil dressing.",
      "price": 9.25,
      "rating": 4.5,
      "reviews": 186,
      "image": "https://images.unsplash.com/photo-1542444459-db19be2ef9b9?auto=format&fit=crop&w=800&q=80",
      "category": "Salads",
      "ingredients": [
        "Cucumber",
        "Tomato",
        "Olives",
        "Feta",
        "Onion",
        "Olive Oil"
      ],
      "calories": 300,
      "preparationTime": "5-8 minutes",
      "spicyLevel": 0,
      "vegetarian": true,
      "available": true
    },
    {
      "id": 30,
      "name": "Fresh Lemonade",
      "description": "Classic fresh-squeezed lemonade served over ice with a hint of mint.",
      "price": 3.75,
      "rating": 4.6,
      "reviews": 205,
      "image": "https://images.unsplash.com/photo-1504198453319-5ce911bafcde?auto=format&fit=crop&w=800&q=80",
      "category": "Drinks",
      "ingredients": [
        "Lemon",
        "Water",
        "Sugar",
        "Mint",
        "Ice"
      ],
      "calories": 120,
      "preparationTime": "2-4 minutes",
      "spicyLevel": 0,
      "vegetarian": true,
      "available": true
    }
  ]);
}
