export default function handler(req, res) {
  res.status(200).json([
    {
      "id": 1,
      "name": "Cheeseburger Wendy's Burger",
      "description": "Classic fast food burger with fresh ground beef, melted cheese, crispy lettuce, ripe tomatoes, pickles, and our signature sauce on a toasted sesame seed bun.",
      "price": 8.24,
      "rating": 4.5,
      "reviews": 285,
      "image": "/images/product1.png",
      "category": "Burgers",
      "ingredients": ["Beef Patty", "Cheese", "Lettuce", "Tomato", "Pickles", "Sesame Bun"],
      "calories": 540,
      "preparationTime": "8-12 minutes",
      "spicyLevel": 1,
      "vegetarian": false,
      "available": true
    },
    {
      "id": 2,
      "name": "Hamburger Veggie Burger",
      "description": "Enjoy our delicious Hamburger Veggie Burger made with a plant-based patty, fresh vegetables, and served on a whole wheat bun. Perfect for vegetarians!",
      "price": 9.99,
      "rating": 4.6,
      "reviews": 312,
      "image": "/images/product2.png",
      "category": "Burgers",
      "ingredients": ["Plant-Based Patty", "Lettuce", "Tomato", "Onion", "Avocado", "Whole Wheat Bun"],
      "calories": 420,
      "preparationTime": "6-10 minutes",
      "spicyLevel": 0,
      "vegetarian": true,
      "available": true
    },
    {
      "id": 3,
      "name": "Margherita Pizza",
      "description": "Traditional Italian pizza with fresh mozzarella, tomato sauce, and basil leaves on a thin crust base.",
      "price": 12.50,
      "rating": 4.7,
      "reviews": 456,
      "image": "/images/product3.png",
      "category": "Pizza",
      "ingredients": ["Mozzarella", "Tomato Sauce", "Fresh Basil", "Thin Crust"],
      "calories": 650,
      "preparationTime": "15-20 minutes",
      "spicyLevel": 0,
      "vegetarian": true,
      "available": true
    },
    {
      "id": 4,
      "name": "Grilled Chicken Salad",
      "description": "Fresh mixed greens topped with grilled chicken breast, cherry tomatoes, cucumber, and our house vinaigrette.",
      "price": 11.75,
      "rating": 4.4,
      "reviews": 198,
      "image": "/images/product4.png",
      "category": "Salads",
      "ingredients": ["Grilled Chicken", "Mixed Greens", "Cherry Tomatoes", "Cucumber", "Vinaigrette"],
      "calories": 320,
      "preparationTime": "5-8 minutes",
      "spicyLevel": 0,
      "vegetarian": false,
      "available": true
    },
    {
      "id": 5,
      "name": "Spicy Buffalo Wings",
      "description": "Crispy chicken wings tossed in our signature spicy buffalo sauce, served with celery sticks and blue cheese dip.",
      "price": 13.99,
      "rating": 4.8,
      "reviews": 524,
      "image": "/images/product5.png",
      "category": "Appetizers",
      "ingredients": ["Chicken Wings", "Buffalo Sauce", "Celery", "Blue Cheese Dip"],
      "calories": 480,
      "preparationTime": "12-15 minutes",
      "spicyLevel": 4,
      "vegetarian": false,
      "available": true
    },
    {
      "id": 6,
      "name": "Fish & Chips",
      "description": "Beer-battered cod served with crispy fries, mushy peas, and tartar sauce. A British classic!",
      "price": 15.25,
      "rating": 4.3,
      "reviews": 267,
      "image": "/images/product6.png",
      "category": "Seafood",
      "ingredients": ["Cod Fish", "Beer Batter", "Fries", "Mushy Peas", "Tartar Sauce"],
      "calories": 720,
      "preparationTime": "15-18 minutes",
      "spicyLevel": 0,
      "vegetarian": false,
      "available": false
    }
  ]);
}
